### [R]ead comix
GET http://localhost:3000/comix


### [C]reate comix
POST http://localhost:3000/comix
Content-Type: application/json

{
    "seriesTitle": "Kajko i Kokosz",
    "seriesSubtitle": "",
    "comixTitle": "Woje Mirmiła",
    "displayName": "Kajko i Kokosz - Woje Mirmiła",
    "author": "Janusz Christa",
    "publisher": "Egmont",
    "publishmentYear": 2023,
    "numberOfPages": 41,
    "coverLinkUrl": null,
    "coverHard": false,
    "rating": 7,
    "collected": false,
    "userId": 2
}


### [U]pdate comix
PUT http://localhost:3000/comix
Content-Type: application/json

{
    "id": 5,
    "seriesTitle": "Kajko i Kokosz",
    "seriesSubtitle": "",
    "comixTitle": "Woje Mirmiła",
    "displayName": "Kajko i Kokosz - Woje Mirmiła",
    "author": "Janusz Christa",
    "publisher": "Egmont",
    "publishmentYear": 2023,
    "numberOfPages": 41,
    "coverLinkUrl": null,
    "coverHard": false,
    "rating": 7,
    "collected": true,
    "userId": 3
}


### [D]elete comix
DELETE http://localhost:3000/comix/7


### Sample exception
GET http://localhost:3000/comix/exception
