### [R]ead comixes
GET http://localhost:3000/comixes


### [C]reate comixes
POST http://localhost:3000/comixes
Content-Type: application/json

{
    "seriesTitle": "Kajko i Kokosz",
    "seriesSubtitle": "",
    "comixTitle": "Woje Mirmiła",
    "displayName": "Kajko i Kokosz - Woje Mirmiła",
    "author": "Janusz Christa",
    "publisher": "Egmont",
    "publishmentYear": 2023,
    "numberOfPages": 41,
    "coverHard": false,
    "rating": 7,
    "collected": false
}


### [U]pdate comix
PUT http://localhost:3000/comixes
Content-Type: application/json

{
    "id": 2,
    "seriesTitle": "Kajko i Kokosz",
    "seriesSubtitle": "",
    "comixTitle": "Woje Mirmiła",
    "displayName": "Kajko i Kokosz - Woje Mirmiła",
    "author": "Janusz Christa",
    "publisher": "Egmont",
    "publishmentYear": 2023,
    "numberOfPages": 41,
    "coverHard": false,
    "rating": 7,
    "collected": true
}


### [D]elete comix
DELETE http://localhost:3000/comixes/1


### Sample exception
GET http://localhost:3000/comixes/exception
