INSERT INTO `Comix` (`id`, `comixTitle`, `seriesTitle`, `author`, `publisher`, `publishmentYear`, `numberOfPages`, `coverUrlLink`, `coverHard`, `rating`, `collected`, `userId`) VALUES
(101, 'Złoty puchar - część 1', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 40, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-zloty-puchar-cz-1.webp', FALSE, 8, TRUE, 1),
(102, 'Złoty puchar - część 2', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 40, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-zloty-puchar-cz-2.webp', FALSE, 8, TRUE, 1),
(103, 'Złoty puchar - część 3', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 39, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-zloty-puchar-cz-3.webp', FALSE, 8, TRUE, 1),
(104, 'Woje Mirmila - część 1', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 40, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-woje-mirmila-cz-1.webp', FALSE, 8, TRUE, 1),
(105, 'Woje Mirmila - część 2', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 40, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-woje-mirmila-cz-2.webp', FALSE, 8, TRUE, 1),
(106, 'Woje Mirmila - część 3', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 37, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-woje-mirmila-cz-3.webp', FALSE, 8, TRUE, 1),
(107, 'Szranki i konkury - część 1', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 55, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-szranki-i-konkury-cz-1.webp', FALSE, 9, TRUE, 1),
(108, 'Szranki i konkury - część 2', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 55, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-szranki-i-konkury-cz-2.webp', FALSE, 9, TRUE, 1),
(109, 'Szranki i konkury - część 3', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 55, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-szranki-i-konkury-cz-3.jpg', FALSE, 9, TRUE, 1),
(110, 'Szkoła latania', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 35, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-szkola-latania.webp', FALSE, 8, TRUE, 1),
(111, 'Wielki turniej', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 35, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-wielki-turniej.webp', FALSE, 8, TRUE, 1),
(112, 'Na wczasach', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 35, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-na-wczasach.webp', FALSE, 8, TRUE, 1),
(113, 'Zamach na Milusia', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 38, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-zamach-na-milusia.webp', FALSE, 9, TRUE, 1),
(114, 'Skarby Mirmiła', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 43, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-skarby-mirmila.webp', FALSE, 8, TRUE, 1),
(115, 'Cudowny lek', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 43, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-cudowny-lek.webp', FALSE, 7, TRUE, 1),
(116, 'Festiwal czarownic', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 40, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-festiwal-czarownic.webp', FALSE, 7, TRUE, 1),
(117, 'Dzień śmiechały', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 40, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-dzien-smiechaly.webp', FALSE, 9, TRUE, 1),
(118, 'W krainie borostworów', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 48, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-w-krainie-borostworow.webp', FALSE, 7, TRUE, 1),
(119, 'Mirmił w opałach', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2017, 47, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-mirmil-w-opalach.webp', FALSE, 7, TRUE, 1),
(120, 'Urodziny Milusia', 'Kajko i Kokosz', 'Janusz Christa', 'EGMONT Polska', 2021, 30, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-urodziny-milusia.webp', FALSE, 7, TRUE, 1),
(121, 'Obłęd Hegemona', 'Kajko i Kokosz', 'Różni wg Janusza Christy', 'EGMONT Polska', 2021, 36, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-obled-hegemona.webp', FALSE, 3, TRUE, 1),
(122, 'Łamignat straszliwy', 'Kajko i Kokosz', 'Różni wg Janusza Christy', 'EGMONT Polska', 2021, 38, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-lamignat-straszliwy.webp', FALSE, 4, TRUE, 1),
(123, 'Królewska Konna', 'Kajko i Kokosz', 'Maciej Kur, Sławomir Kiełbus, Piotr Bednarczyk', 'EGMONT Polska', 2021, 44, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-krolewska-konna.webp', FALSE, 5, TRUE, 1),
(124, 'Zaćmienie i zmierzchu', 'Kajko i Kokosz', 'Maciej Kur, Sławomir Kiełbus, Piotr Bednarczyk', 'EGMONT Polska', 2021, 46, 'assets/cover/kajko-i-kokosz/kajko-i-kokosz-zacmienie-zmierzchu.webp', FALSE, 6, TRUE, 1),
(201, 'Zabłąkana rakieta', 'Kajtek i Koko', 'Janusz Christa', 'EGMONT Polska', 2018, 92, 'assets/cover/kajtek-i-koko/kajtek-i-koko-zablakana-rakieta.webp', FALSE, 4, TRUE, 1),
(202, 'Twierdza tyrana', 'Kajtek i Koko', 'Janusz Christa', 'EGMONT Polska', 2018, 92, 'assets/cover/kajtek-i-koko/kajtek-i-koko-twierdza-tyrana.webp', FALSE, 4, TRUE, 1),
(203, 'Przyjaciel Jol', 'Kajtek i Koko', 'Janusz Christa', 'EGMONT Polska', 2018, 92, 'assets/cover/kajtek-i-koko/kajtek-i-koko-przyjaciel-jol.webp', FALSE, 4, TRUE, 1),
(204, 'Planeta automatów', 'Kajtek i Koko', 'Janusz Christa', 'EGMONT Polska', 2020, 92, 'assets/cover/kajtek-i-koko/kajtek-i-koko-planeta-automatow.webp', FALSE, 5, TRUE, 1),
(205, 'Obce świadomości', 'Kajtek i Koko', 'Janusz Christa', 'EGMONT Polska', 2020, 92, 'assets/cover/kajtek-i-koko/kajtek-i-koko-obce-swiadomosci.webp', FALSE, 5, TRUE, 1),
(206, 'Dwór Apodyktusa', 'Kajtek i Koko', 'Janusz Christa', 'EGMONT Polska', 2020, 92, 'assets/cover/kajtek-i-koko/kajtek-i-koko-dwor-apodyktusa.webp', FALSE, 5, TRUE, 1),
(207, 'Bogini moczarów', 'Kajtek i Koko', 'Janusz Christa', 'EGMONT Polska', 2020, 92, 'assets/cover/kajtek-i-koko/kajtek-i-koko-bogini-moczarow.webp', FALSE, 5, TRUE, 1),
(301, 'Raissa', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2018, 46, 'assets/cover/thorgal-louve/thorgal-louve-01-raissa.webp', TRUE, 7, TRUE, 1),
(302, 'Dłoń boga Tyra', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2018, 46, 'assets/cover/thorgal-louve/thorgal-louve-02-dlon-boga-tyra.webp', TRUE, NULL, TRUE, 1),
(303, 'Królestwo chaosu', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2013, 46, 'assets/cover/thorgal-louve/thorgal-louve-03-krolestwo-chaosu.jpg', TRUE, NULL, TRUE, 1),
(304, 'Crow', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2014, 46, 'assets/cover/thorgal-louve/thorgal-louve-04-crow.jpg', TRUE, NULL, TRUE, 1),
(305, 'Skald', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2015, 46, 'assets/cover/thorgal-louve/thorgal-louve-05-skald.jpg', TRUE, NULL, TRUE, 1),
(306, 'Królowa czarnych elfów', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2018, 46, 'assets/cover/thorgal-louve/thorgal-louve-06-krolowa-czarnych-elfow.jpg', TRUE, NULL, TRUE, 1),
(307, 'Nidhogg', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2020, 46, 'assets/cover/thorgal-louve/thorgal-louve-07-nidhogg.jpg', TRUE, NULL, TRUE, 1),
(311, 'Trzy siostry Minkelsonn', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2017, 46, 'assets/cover/thorgal-mlodziencze-lata/thorgal-mlodziencze-lata-01-trzy-siostry-minkelsonn.jpg', TRUE, 7, TRUE, 1),
(312, 'Oko Odyna', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2014, 46, 'assets/cover/thorgal-mlodziencze-lata/thorgal-mlodziencze-lata-02-oko-odyna.webp', TRUE, 6, TRUE, 1),
(313, 'Runa', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2020, 46, 'assets/cover/thorgal-mlodziencze-lata/thorgal-mlodziencze-lata-03-runa.webp', TRUE, 7, TRUE, 1),
(314, 'Berserkerowie', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2018, 46, 'assets/cover/thorgal-mlodziencze-lata/thorgal-mlodziencze-lata-04-berserkerowie.jpg', TRUE, 6, TRUE, 1),
(315, 'Slivia', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2019, 46, 'assets/cover/thorgal-mlodziencze-lata/thorgal-mlodziencze-lata-05-slivia.jpg', TRUE, 7, TRUE, 1),
(316, 'Lodowy drakkar', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2018, 46, 'assets/cover/thorgal-mlodziencze-lata/thorgal-mlodziencze-lata-06-lodowy-drakkar.jpg', TRUE, 7, TRUE, 1),
(317, 'Sinozęby', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2019, 46, 'assets/cover/thorgal-mlodziencze-lata/thorgal-mlodziencze-lata-07-sinozeby.webp', TRUE, 6, TRUE, 1),
(318, 'Bękarty', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2020, 46, 'assets/cover/thorgal-mlodziencze-lata/thorgal-mlodziencze-lata-08-bekarty.webp', TRUE, 7, TRUE, 1),
(319, 'Łzy Hel', 'Thorgal', 'Roman Surżenko, Pennetier Yann', 'EGMONT Polska', 2021, 46, 'assets/cover/thorgal-mlodziencze-lata/thorgal-mlodziencze-lata-09-lzy-hel.webp', TRUE, 6, TRUE, 1),
(407, 'Walka wodzów', 'Asteriks', 'Rene Goscinny, Albert Uderzo', 'EGMONT Polska', 2020, 44, 'assets/cover/asteriks/asteriks-walka-wodzow.webp', FALSE, 7, TRUE, 1),
(409, 'Asteriks i Normanowie', 'Asteriks', 'Rene Goscinny, Albert Uderzo', 'EGMONT Polska', 2020, 44, 'assets/cover/asteriks/asteriks-i-normanowie.webp', FALSE, 7, TRUE, 1),
(415, 'Niezgoda', 'Asteriks', 'Rene Goscinny, Albert Uderzo', 'EGMONT Polska', 2012, 44, 'assets/cover/asteriks/asteriks-niezgoda.webp', FALSE, 7, TRUE, 1),
(422, 'Wielka przeprawa', 'Asteriks', 'Rene Goscinny, Albert Uderzo', 'EGMONT Polska', 2021, 45, 'assets/cover/asteriks/asteriks-wielka-przeprawa.webp', FALSE, 7, TRUE, 1),
(423, 'Obeliks i spółka', 'Asteriks', 'Rene Goscinny, Albert Uderzo', 'EGMONT Polska', 2021, 45, 'assets/cover/asteriks/asteriks-obeliks-i-spolka.webp', FALSE, 7, TRUE, 1),
(424, 'Asteriks u Belgów', 'Asteriks', 'Rene Goscinny, Albert Uderzo', 'EGMONT Polska', 2013, 44, 'assets/cover/asteriks/asteriks-u-belgow.webp', FALSE, 7, TRUE, 1),
(425, 'Wielki rów', 'Asteriks', 'Albert Uderzo', 'EGMONT Polska', 2012, 44, 'assets/cover/asteriks/asteriks-wielki-row.webp', FALSE, 7, TRUE, 1),
(426, 'Odyseja Asteriksa', 'Asteriks', 'Albert Uderzo', 'EGMONT Polska', 2022, 44, 'assets/cover/asteriks/asteriks-odyseja-asteriksa.webp', FALSE, 7, TRUE, 1),
(427, 'Syn Asteriksa', 'Asteriks', 'Albert Uderzo', 'EGMONT Polska', 2012, 44, 'assets/cover/asteriks/asteriks-syn-asteriksa.webp', FALSE, 7, TRUE, 1),
(429, 'Róża i miecz', 'Asteriks', 'Albert Uderzo', 'EGMONT Polska', 2012, 44, 'assets/cover/asteriks/asteriks-roza-i-miecz.webp', FALSE, 7, TRUE, 1),
(431, 'Asteriks i Latraviata', 'Asteriks', 'Albert Uderzo', 'EGMONT Polska', 2013, 48, 'assets/cover/asteriks/asteriks-i-latraviara.webp', FALSE, 8, TRUE, 1),
(432, 'Galijskie początki', 'Asteriks', 'Rene Goscinny, Albert Uderzo', 'EGMONT Polska', 2013, 55, 'assets/cover/asteriks/asteriks-galijskie-poczatki.webp', FALSE, 6, TRUE, 1),
(433, 'Kiedy niebo spada na głowę', 'Asteriks', 'Albert Uderzo', 'EGMONT Polska', 2013, 44, 'assets/cover/asteriks/asteriks-kiedy-niebo-spada-na-glowe.webp', FALSE, 7, TRUE, 1),
(434, 'Rocznica urodzin Asteriksa i Obeliksa - Złota księga', 'Asteriks', 'Rene Goscinny, Albert Uderzo', 'EGMONT Polska', 2023, 49, 'assets/cover/asteriks/asteriks-rocznica-urodzin-asteriksa-i-obeliksa-zlota-ksiega.webp', FALSE, 7, TRUE, 1),
(435, 'Asteriks u Piktów', 'Asteriks', 'Jean-Yves Ferri, Didier Conrad', 'EGMONT Polska', 2022, 44, 'assets/cover/asteriks/asteriks-u-piktow.webp', FALSE, 5, TRUE, 1),
(436, 'Papirus Cezara', 'Asteriks', 'Jean-Yves Ferri, Didier Conrad', 'EGMONT Polska', 2021, 44, 'assets/cover/asteriks/asteriks-papirus-cezara.webp', FALSE, 6, TRUE, 1),
(437, 'Asteriks w Italii', 'Asteriks', 'Jean-Yves Ferri, Didier Conrad', 'EGMONT Polska', 2020, 45, 'assets/cover/asteriks/asteriks-w-italii.webp', FALSE, 5, TRUE, 1),
(438, 'Córka Wercyngetoryksa', 'Asteriks', 'Jean-Yves Ferri, Didier Conrad', 'EGMONT Polska', 2021, 44, 'assets/cover/asteriks/asteriks-corka-wercyngetoryksa.webp', FALSE, 5, TRUE, 1),
(490, 'W tej dzielnicy żadnej łaciny', 'Asteriks', 'Różni autorzy na podst. Rene Goscinny, Albert Uderzo', 'EGMONT Polska', 2022, 64, 'assets/cover/asteriks/idefiks-i-nieugieci-w-tej-dzielnicy-zadnej-laciny.webp', FALSE, 6, TRUE, 1),
(515, 'Ucieczka Daltonów', 'Lucky Luke', 'Morris, Rene Goscinny', 'EGMONT Polska', 2019, 44, 'assets/cover/lucky-luke/lucky-luke-ucieczka-daltonow.webp', FALSE, 6, TRUE, 1),
(517, 'Na tropie Daltonów', 'Lucky Luke', 'Morris, Rene Goscinny', 'EGMONT Polska', 2020, 44, 'assets/cover/lucky-luke/lucky-luke-na-tropie-daltonow.webp', FALSE, NULL, TRUE, 1),
(522, 'Daltonowie i zamieć', 'Lucky Luke', 'Morris, Rene Goscinny', 'EGMONT Polska', 2021, 44, 'assets/cover/lucky-luke/lucky-luke-daltonowie-i-zamiec.webp', FALSE, NULL, TRUE, 1),
(534, 'Dalton City', 'Lucky Luke', 'Morris, Rene Goscinny', 'EGMONT Polska', 2018, 45, 'assets/cover/lucky-luke/lucky-luke-dalton-city.webp', FALSE, NULL, TRUE, 1),
(538, 'Mama Dalton', 'Lucky Luke', 'Morris, Rene Goscinny', 'EGMONT Polska', 2017, 44, 'assets/cover/lucky-luke/lucky-luke-mama-dalton.webp', FALSE, NULL, TRUE, 1),
(544, 'Daltonowie na kuracji', 'Lucky Luke', 'Morris, Rene Goscinny', 'EGMONT Polska', 2018, 44, 'assets/cover/lucky-luke/lucky-luke-daltonowie-na-kuracji.webp', FALSE, NULL, TRUE, 1),
(547, 'Skarb Daltonów', 'Lucky Luke', 'Morris, Vicq', 'EGMONT Polska', 2018, 44, 'assets/cover/lucky-luke/lucky-luke-skarb-daltonow.jpg', FALSE, NULL, TRUE, 1),
(555, 'Ballada o Daltonach i inne opowieści', 'Lucky Luke', 'Morris, Rene Goscinny, Greg', 'EGMONT Polska', 2017, 46, 'assets/cover/lucky-luke/lucky-luke-ballada-o-daltonach-i-inne-opowiesci.webp', FALSE, NULL, TRUE, 1),
(560, 'Daltonowie tracą pamięć', 'Lucky Luke', 'Morris, Xavier Fauche, Jean Leturgie', 'EGMONT Polska', 2018, 44, 'assets/cover/lucky-luke/lucky-luke-daltonowie-traca-pamiec.webp', FALSE, NULL, TRUE, 1),
(576, 'Wujaszkowie Dalton', 'Lucky Luke', 'Achde, Laurent Gerra, Jacques Pessis', 'EGMONT Polska', 2017, 44, 'assets/cover/lucky-luke/lucky-luke-wujaszkowie-dalton.jpg', FALSE, NULL, TRUE, 1),
(601, 'Niech żyje wyobraźnia', 'Jonka, Jonek i Kleks', 'Szarlota Pawel', 'EGMONT Polska', 2020, 62, 'assets/cover/jonka-jonek-i-kleks/jonka-jonek-i-kleks-niech-zyje-wyobraznia.jpg', FALSE, 5, TRUE, 1),
(602, 'Porwanie księżniczki', 'Jonka, Jonek i Kleks', 'Szarlota Pawel', 'EGMONT Polska', 2016, 62, 'assets/cover/jonka-jonek-i-kleks/jonka-jonek-i-kleks-porwanie-ksiezniczki.webp', FALSE, 6, TRUE, 1),
(603, 'Pióro kontra flamaster', 'Jonka, Jonek i Kleks', 'Szarlota Pawel', 'EGMONT Polska', 2021, 60, 'assets/cover/jonka-jonek-i-kleks/jonka-jonek-i-kleks-pioro-kontra-flamaster.webp', FALSE, 6, TRUE, 1),
(604, 'Smocze jajo', 'Jonka, Jonek i Kleks', 'Szarlota Pawel', 'EGMONT Polska', 2016, 61, 'assets/cover/jonka-jonek-i-kleks/jonka-jonek-i-kleks-smocze-jajo.webp', FALSE, 6, TRUE, 1),
(701, 'Straszne smoczysko', 'Oskar i Fabrycy', 'Mieczysław Fijał', 'EGMONT Polska', 2017, 38, 'assets/cover/oskar-i-fabrycy/oskar-i-fabrycy-straszne-smoczysko.webp', FALSE, 5, TRUE, 1),
(702, 'Dyliżans widmo', 'Oskar i Fabrycy', 'Mieczysław Fijał, Maciej Kur', 'EGMONT Polska', 2018, 38, 'assets/cover/oskar-i-fabrycy/oskar-i-fabrycy-dylizans-widmo.webp', FALSE, 6, TRUE, 1),
(801, 'Z życia Smerfów', 'Przygody Smerfów', 'Peyo, Yvan Delporte', 'EGMONT Polska', 2019, 52, 'assets/cover/przygody-smerfow/przygody-smerfow-z-zycia-smerfow.jpg', FALSE, 6, TRUE, 1),
(802, 'Kruk', 'Przygody Smerfów', 'Alain Maury, Luc Parthoens, Thierry Culliford', 'EGMONT Polska', 2019, 52, 'assets/cover/przygody-smerfow/przygody-smerfow-smerfy-i-wioska-dziewczyn-kruk.jpg', FALSE, 6, TRUE, 1),
(901, 'Umpa-Pa czerwonoskóry', 'Różne', 'Rene Goscinny, Albert Uderzo', 'EGMONT Polska', 2007, 176, 'assets/cover/rozne/umpa-pa-czerwonoskory.webp', TRUE, 6, TRUE, 1);